//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketBooking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
        public int IdStatus { get; set; }
        public string StatusPerjalanan { get; set; }
        public int Harga { get; set; }
        public int Ranking { get; set; }
    }
}
